### Makefile for sqlparser

# Ensure GOPATH is set before running build process.
ifeq "$(GOPATH)" ""
  $(error Please set the environment variable GOPATH before running `make`)
endif

path_to_add := $($(GOPATH))
export PATH := $(path_to_add):$(PATH)


GOLEX   := golex
GOYACC  := goyacc
GOLINT  := golint

GO        := GO15VENDOREXPERIMENT="1" go
ARCH      := "`uname -s`"
LINUX     := "Linux"
MAC       := "Darwin"
PACKAGES  := $$(go list ./...| grep -vE 'vendor')

.PHONY:  parser goyacc golex


all: parser 

golex:
	$(GO) get github.com/qiuyesuifeng/golex

goyacc:
	$(GO) install github.com/ruiaylin/sqlparser/parser/goyacc


TEMP_FILE = temp_parser_file

parser: goyacc golex
	$(GOYACC) -o /dev/null -xegen $(TEMP_FILE) parser/parser.y
	$(GOYACC) -o parser/parser.go -xe $(TEMP_FILE) parser/parser.y 2>&1 | egrep "(shift|reduce)/reduce" | awk '{print} END {if (NR > 0) {print "Find conflict in parser.y. Please check y.output for more information."; system("rm -f $(TEMP_FILE)"); exit 1;}}'
	rm -f $(TEMP_FILE)
	rm -f y.output

	@if [ $(ARCH) = $(LINUX) ]; \
	then \
		sed -i -e 's|//line.*||' -e 's/yyEofCode/yyEOFCode/' parser/parser.go; \
	elif [ $(ARCH) = $(MAC) ]; \
	then \
		/usr/bin/sed -i "" 's|//line.*||' parser/parser.go; \
		/usr/bin/sed -i "" 's/yyEofCode/yyEOFCode/' parser/parser.go; \
	fi
	$(GOLEX) -o parser/scanner.go parser/scanner.l
	@awk 'BEGIN{print "// Code generated by goyacc"} {print $0}' parser/parser.go > tmp_parser.go && mv tmp_parser.go parser/parser.go;
	@awk 'BEGIN{print "// Code generated by goyacc"} {print $0}' parser/scanner.go > tmp_scanner.go && mv tmp_scanner.go parser/scanner.go;
